"""added user_roles

Revision ID: bc73e16a3d77
Revises: 2c322065e3b2
Create Date: 2024-05-18 20:39:16.102812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc73e16a3d77'
down_revision: Union[str, None] = '2c322065e3b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_role', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['user_role'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'user_role')
    # ### end Alembic commands ###
